#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE}")" &>/dev/null && pwd)
APP_DIR=$(cd -- "${SCRIPT_DIR}/../.." &>/dev/null && pwd)

./script/app test
[ ! -z "$(grep -iE "error|failure" "storage/logs/unit-test.log")" ] && exit 1

LOG_RDIR="storage/logs"
LOG_FILES=("laravel.log")

for LOG_FILE in "${LOG_FILES[@]}"; do
    FILE="${APP_DIR}/${LOG_RDIR}/${LOG_FILE}"
    [ ! -f "${FILE}" ] && continue
    if [[ $(cat "${FILE}" | wc -l) -ne 0 ]]; then
        echo "Please review the errors in \"${LOG_RDIR}/${LOG_FILE}\"."
        echo
        grep -r 'ERROR' "${LOG_RDIR}/${LOG_FILE}"
        exit 1
    fi
done

exit 0